before_commands:
    - composer install --dev

tools:
    php_cs_fixer: true
    php_cpd: true
    php_code_coverage: true
    php_code_sniffer:
        config:
            standard: PSR2
    php_mess_detector: true
    php_analyzer:
        filter:
            excluded_paths: ["*/Tests/*","*/Resources/doc/*","*/vendor/*"]
    sensiolabs_security_checker: true
