language: php

env:
    - SYMFONY_VERSION="2.1.*"
    - SYMFONY_VERSION="2.2.*"
    - SYMFONY_VERSION="2.3.*"
    - SYMFONY_VERSION="2.4.*"
    - SYMFONY_VERSION="2.5.*"

before_script:
  - COMPOSER_ROOT_VERSION=dev-master
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --dev

php:
  - 5.3
  - 5.4
  - 5.5
